### PR TITLE
Feature-gate `iota-client` dependency, integrate `StardustDID`

### PR DESCRIPTION
**Pull request by cycraig**
# Description of change
Integrates `StardustDocument` with `StardustDID` introduced in #949. Also simplifies the public API of `StardustDID` somewhat to reduce the work needed for the future Wasm bindings. The `"iota-client"` feature-gate is to prevent potential compilation errors in the future, and would be good to have in general.

### Added

- Add `"iota-client"` feature to `identity_stardust`.

### Changed

- Change `StardustDocument::new` to take `NetworkName`.
- Make `StardustDID` functions `check_method`, `check_method_id`, and `check_network` private.
- Move `StardustDocument::did_from_block` to `StardustDID::from_block`.
- Rename and feature-gate `StardustDocument::deserialize_from_output` to `unpack_from_output`.

### Removed

- Remove `StardustDocument::placeholder_did`.
- Remove `StardustDID::with_network_name` - it had a bug where setting the default network "main" would not be normalised.

## Links to any relevant issues
Part of #908.

## Type of change

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] Enhancement (a non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Fix

## How the change has been tested
Unit tests pass with default features, `cargo test --no-default-features` (when example is removed, otherwise fails to compile), and `cargo test --all-features` (same as default).

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: identity_stardust/src/document/stardust_document.rs [hunk 1]
```diff
@@ -311,63 +287,35 @@ impl StardustDocument {
...
+    /// NOTE: `did` is required since it is omitted from the serialized DID Document and
+    /// cannot be inferred from the [`Output`]. It also indicates the network, which is not
+    /// encoded in the `AliasId` alone.
+    // TODO: remove? Is `unpack` sufficient?
+    pub fn unpack_from_output(did: &StardustDID, output: &Output) -> Result<StardustDocument> {
+      let document: &[u8] = match output {
+        Output::Alias(alias_output) => alias_output.state_metadata(),
+        _ => return Err(Error::InvalidStateMetadata("not an alias output")),
+      };
+      Self::unpack(did, document)
```
Comment (PhilippGackstatter) [inline identity_stardust/src/document/stardust_document.rs:317]: It's convenient. I'd leave it in for now and see if we really need it when we write more examples.

**Review by PhilippGackstatter — APPROVED** [review]
Looks good to me.

File: identity_stardust/src/document/stardust_document.rs [hunk 2]
```diff
@@ -80,10 +61,12 @@ impl StardustDocument {
   // Constructors
   // ===========================================================================
 
-  /// Constructs an empty DID Document with a [`StardustDocument::placeholder_did`] identifier.
+  /// Constructs an empty DID Document with a [`StardustDID::placeholder`] identifier
+  /// for the given `network`.
   // TODO: always take Option<NetworkName> or `new_with_options` for a particular network?
-  pub fn new() -> Self {
-    Self::new_with_id(Self::placeholder_did().clone())
+  // TODO: store the network in the serialized state metadata? Currently it's lost during packing.
```
[the remark this answers is not in the document]
Comment (cycraig) [reply identity_stardust/src/document/stardust_document.rs:67]: I'm still unsure whether it's good or bad that the network is not embedded. Since the network (other than official names like "main", "dev", etc.) is determined by the client, you could name the network anything and resolve the DID for it. One could change the network name of their private Tangle without affecting the DIDs already on it.

We also have the problem of not matching the network names anymore, e.g. current mainnet has `network_id: "chrysalis-mainnet", bech32_hrp: "iota"`, while current Shimmer alphanet uses `network_name: "alphanet-9", bech32_hrp: "rms"`. Should we switch to the `bech32_hrp` maybe? Then `iota` will be the canonical mainnet that is normalised away, so `did:iota:iota:0x123 = did:iota:0x123`.

File: identity_stardust/src/did/stardust_did.rs [hunk 3]
```diff
@@ -193,18 +217,55 @@ impl StardustDID {
...
+              index
+                .try_into()
+                .map_err(|_| DIDError::Other("output index exceeds u16"))?,
+            )?);
+          }
+        }
+        Err(DIDError::Other("no alias output in transaction essence"))?
+      }
+      _ => Err(DIDError::Other("not a transaction payload"))?,
+    }
```
Comment (olivereanderson) [inline identity_stardust/src/did/stardust_did.rs:268]: nit: I find this more readable. Optional. 

```suggestion 
    if let Payload::Transaction(tx_payload) = payload {
      let TransactionEssence::Regular(regular) = tx_payload.essence();
      if let Some((index, _)) = regular
        .outputs()
        .iter()
        .enumerate()
        .find(|(_, item)| matches!(item, Output::Alias(_)))
      {
        Ok(OutputId::new(
          tx_payload.id(),
          index
            .try_into()
            .map_err(|_| DIDError::Other("output index exceeds u16"))?,
        )?)
      } else {
        Err(DIDError::Other("no alias output in transaction essence"))?
      }
    } else {
      Err(DIDError::Other("not a transaction payload"))?
    }
```

File: identity_stardust/src/state_metadata/document.rs [hunk 4]
```diff
@@ -35,21 +36,22 @@ pub(crate) struct StateMetadataDocument {
...
-    let core_document: StardustCoreDocument = document.map(
+    let core_document: StardustCoreDocument = document.try_map(
       // Replace placeholder identifiers.
       |did| {
         if did == PLACEHOLDER_DID.as_ref() {
-          original_did.clone()
+          Ok(original_did.clone())
         } else {
-          did
+          // TODO: wrap error?
```
Comment (olivereanderson) [inline identity_stardust/src/state_metadata/document.rs:47]: If there was no internal use of this method it would be fine to leave it as is as then the context is clear to the caller. Currently we call this method in `StardustDocument::unpack`, but I am not sure to which extent more context is useful for the caller in that case.

**Review by olivereanderson — APPROVED** [review]
Looks good to me.

File: identity_stardust/src/document/stardust_document.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (PhilippGackstatter) [reply identity_stardust/src/document/stardust_document.rs:67]: Good point. In general I like the approach of letting the client determine the network. In theory the HRP sounds nice, but as you pointed out, it's not necessarily unique. It doesn't seem like it would be a problem for the "important" networks we'll be on like `iota` and `smr`; those should be unambiguous. I imagine it's mainly an issue for test networks (i.e. Does `rms` mean the alphanet or the testnet?) where it seems fine to just trust the user to point the client to the right network?

Regardless of hrp or network name, we can set the network name or hrp during resolution so it won't have to be serialized.

[the remark this answers is not in the document]
Comment (cycraig) [reply identity_stardust/src/document/stardust_document.rs:67]: Okay, will leave the network omitted for now to be determined during resolution. We can revisit the decision if there problems come up. 

The main thing might be inconsistent DIDs within the same network. E.g. Alice signs a credential with their DID `did:iota:alphanet:...` but Bob resolves Alice's DID using a different network like `did:iota:alpha:...`, so either resolution fails (due to unrecognised network) or it is resolved with `alpha` instead of `alphanet` but credential verification fails due to the mismatched network.

[the remark this answers is not in the document]
Comment (PhilippGackstatter) [reply identity_stardust/src/document/stardust_document.rs:67]: True that, but the HRP for the network should be the same since it's retrieved from the node, so would this actually occur in practice?

[the remark this answers is not in the document]
Comment (cycraig) [reply identity_stardust/src/document/stardust_document.rs:67]: Sure, but that's only if we use only an HRP instead of a network name (but again, the HRP has its own problems with potentially matching multiple networks/chains).
